name = "lys"
author = "lys team"
description = "a vcs"
version = "0.2.0"
arch = "x86_64"
license = "APGL-3.0"
icon = "lys.svg"
output = "dist"
provides = ["syl", "lys"]
depends = ["rust", "blake3", "sqlite", "tar", "libgit2", "openssl"]
optional = ["git"]
conflicts = []
replaces = ["lys", "syl"]
homepage = "https://github.com/hackia/lys/wiki"
repository = "https://github.com/hackia/lys"
